#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BACKGROUNDSCRIPT,
	BULLETMGRSCRIPT,
	BULLETSCRIPT,
	BACKGROUNDTILE,
	CAMMOVESCRIPT,
	CHARACTERANIMHANDLER,
	CHARACTERSCRIPT,
	ENEMYANIMHANDLER,
	ENEMYSCRIPT,
	PLAYERANIMHANDLER,
	PLAYERSCRIPT,
	PLAYERWEAPONHANDLER,
	EQUIPMENTSCRIPT,
	INVENSCRIPT,
	STRUCTUREHANDLER,
	WEAPONMINIGUN,
	WEAPONPISTOL,
	WEAPONROCKET,
	WEAPONSCRIPT,
	WEAPONSHOTGUN,
	WEAPONUZI,
	MONSTERSCRIPT,
	FLIPBOOKEFFECTSCRIPT,
	MUZZLEFLASHSCRIPT,
	MUZZLESMOKESCRIPT,
	EXPLOSIONDOME,
	OBSTACLE,
	ROCKETPROJECTILE,
	CHARACTERSTAT,
	STATSCRIPT,
	STRUCTURESTAT,
	ENEMYSTAT,
	PLAYERSTAT,
	BARREL,
	STRUCTURE,
	TURRET,
	END,
};

using namespace std;
class CScript;

class ScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
