#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	BACKGROUNDSCRIPT,
	BULLETMGRSCRIPT,
	BULLETSCRIPT,
	AIRSTRIKE,
	BACKGROUNDTILE,
	CAMMOVESCRIPT,
	CHARACTERANIMHANDLER,
	ENEMYANIMHANDLER,
	PLAYERANIMHANDLER,
	CHARACTERSCRIPT,
	CHARACTERSTAT,
	ENEMYSTAT,
	PLAYERSTAT,
	ENEMYSCRIPT,
	DEVIL,
	FLAMELINEHANDLER,
	ENEMYSPAWNHANDLER,
	MUMMY,
	PERCEPTIONHANDLER,
	RUNNER,
	VAMPIRE,
	PLAYERSCRIPT,
	PLAYERWEAPONHANDLER,
	EQUIPMENTSCRIPT,
	INVENSCRIPT,
	STRUCTUREHANDLER,
	WEAPONMINIGUN,
	WEAPONPISTOL,
	WEAPONROCKET,
	WEAPONSCRIPT,
	WEAPONSHOTGUN,
	WEAPONUZI,
	MONSTERSCRIPT,
	FLIPBOOKEFFECTSCRIPT,
	MUZZLEFLASHSCRIPT,
	MUZZLESMOKESCRIPT,
	EXPLOSION,
	EXPLOSIONDOME,
	FIREPILLARHANDLER,
	FIRSTSPAWNLOCMANAGER,
	OBSTACLE,
	GRENADE,
	ROCKETPROJECTILE,
	ROUNDHANDLER,
	STATSCRIPT,
	BARREL,
	STRUCTURE,
	TURRET,
	STRUCTURESTAT,
	BUTTON,
	GAMEUI,
	PROGRESSBAR,
	TEXT,
	END,
};

using namespace std;
class CScript;

class ScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
